[project]
name = "dbt-enpal-assessment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-postgres>=1.10.0",
]

[dependency-groups]
dev = [
    "sqlfluff>=4.0.4",
    "sqlfluff-templater-dbt>=4.0.4",
]
